# Generated by Django 4.2.5 on 2023-11-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_folder_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
