# Generated by Django 4.2.5 on 2023-11-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_task_folder_delete_folder_delete_task'),
        ('myapp', '0002_folder_task_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
