# Generated by Django 4.2.5 on 2023-11-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_folder_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
