# Generated by Django 4.2.5 on 2023-11-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
